; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:cyd]
platform = espressif32
board = esp32-2432S028C
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps = 
    bodmer/TFT_eSPI @ ^2.5.43

build_flags = 
    -DUSER_SETUP_LOADED=1
    -Iinclude
    -DTOUCH_CS=33