#ifdef T_EMBED_1101
#include "lilygo-t-embed-cc1101.h"
#elif T_WATCH_S3
#include "lilygo-t-watch-s3.h"
#elif ARDUINO_T_WATCH_S3_ULTRA
#include "lilygo-t-watch-ultra.h"
#elif T_EMBED
#include "lilygo-t-embed.h"
#elif T_DECK
#include "lilygo-t-deck.h"
#elif T_LORA_PAGER
#include "lilygo-t-lora-pager.h"
#elif ARDUINO_M5STACK_CARDPUTER
#include "m5stack-cardputer.h"
#elif defined(PANCAKE)
#include "pancake.h"
#elif defined(NM_CYD_C5) || defined(CONFIG_IDF_TARGET_ESP32C5)
#include "nm-cyd-c5.h"
#elif CYD
#include "CYD-2432S028.h"
#elif ARDUINO_M5STACK_CORE
#include "m5stack-core.h"
#elif ARDUINO_M5STACK_CORES3
#include "m5stack-cores3.h"
#elif ARDUINO_M5STACK_CORE2
#include "m5stack-core2.h"
#elif ARDUINO_M5STICK_C_PLUS
#include "m5stack-cplus1_1.h"
#elif ARDUINO_M5Stick_C
#include "m5stack-c.h"
#elif ARDUINO_M5STICK_C_PLUS2
#include "m5stack-cplus2.h"
#elif ESP32S3DEVKITC1
#include "ESP32S3-General.h"
#elif CYDS3
#include "esp32s3.h"
#elif ESP32S3_4M
#include "ESP32S3-4M.h"
#elif ESP32_DEV
#include "esp32dev.h"
#elif MARAUDERMINI
#include "marauder-mini.h"
#elif MARAUDERV4
#include "marauder-v4og.h"
#elif T_DISPLAY_S3_TOUCH
#include "lilygo-t-display-s3-touch.h"
#elif T_DONGLE_S3
#include "lilygo-t-dongle-s3-tft.h"
#elif WAVESHARE_ESP32_S3_LCD_147
#include "waveshare-esp32-s3-lcd-147.h"
#elif T_DISPLAY_S3_PRO
#include "lilygo-t-display-s3-pro.h"
#elif SMOOCHIEE_BOARD
#include "smoochiee-board.h"
#elif REAPER
#include "../reaper/pins_arduino.h"
#elif defined(LYLYGO_T5S3_PRO) || defined(LYLYGO_TDECK_PRO)
#include "esp32s3.h"
#elif LYLYGO_T5
#include "esp32dev.h"
#elif LILYGO_T_HMI
#include "lilygo-t-hmi.h"
#elif ELECROW
#include "elecrow-esp32-24B.h"
#elif ARDUINO_M5STACK_TAB5
#include "m5stack-tab5.h"
#elif ARDUINO_M5STACK_PAPERS3
#include "m5stack-paper-s3.h"
#elif ARDUINO_M5STACK_PAPER
#include "m5stack-paper.h"
#elif ARDUINO_NESSO_N1
#include "arduino-nesso-n1.h"
#elif ARDUINO_M5STACK_STICKS3
#include "m5stack-sticks3.h"
#elif ARDUINO_M5STACK_DINMETER
#include "m5stack-dinmeter.h"
#endif